---
Name: goldfinch-components
After:
  - '#goldfinch-editor-config'
---

SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  extensions:
    - Goldfinch\Components\Extensions\HTMLEditorExtension

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Goldfinch\Components\Extensions\ComponentsAssetsExtension
