---
Name: goldfinch-html-snippets
After:
  - "#goldfinch-editor-config"
---
SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  extensions:
    - Goldfinch\HTMLSnippets\Extensions\HTMLEditorExtension

SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - "goldfinch/html-snippets:client/dist/component.css"

SilverStripe\Forms\HTMLEditor\TinyMCEConfig:
  editor_css:
    - "goldfinch/html-snippets:client/dist/tinymce.css"
